[package]
name = "rusty_kernel"
version = "0.1.0"
edition = "2021"
authors = ["Ronnie Huggins <rjhj@protonmail.com>"]

[dependencies]
bootloader = "0.9"
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"